/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deliverymakanan;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yorozuya
 */
public class OrderMakanan extends javax.swing.JFrame {
    Driver dr;
    Customer cs;
    Order odtemp;
    Order od;
    int i=0;
    long sum=0;
    /**
     * Creates new form OrderMakanan
     */
    public OrderMakanan(Driver dr, Customer cs) {
        initComponents();
        this.setTitle("Order Menu Makanan");
        this.dr=dr;
        this.cs=cs;
        odtemp=new Order();
        //combobuttonmenu
        comboMenu.removeAllItems();
        for(int i=0; i<dr.item.size(); i++){
            if(dr.item.get(i).stock>0){
                comboMenu.addItem(dr.item.get(i).name);
            }
        }
        
    }
    public static String setTime(){
        Calendar cal = Calendar.getInstance();
    	cal.getTime();
    	SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-YYYY");
    	System.out.println( sdf.format(cal.getTime()) );
        return sdf.format(cal.getTime());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBayar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbDel = new javax.swing.JLabel();
        lbHarga = new javax.swing.JLabel();
        comboMenu = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        btTambah = new javax.swing.JButton();
        btSelesai = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbBayar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbBayar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Menu", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tbBayar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 332, 105));

        jLabel1.setText("Total Harga : ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel2.setText("Biaya Delivery :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        lbDel.setText("-");
        jPanel1.add(lbDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 119, -1));

        lbHarga.setText("-");
        jPanel1.add(lbHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 87, -1));

        comboMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMenuActionPerformed(evt);
            }
        });
        jPanel1.add(comboMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel5.setText("Menu Masakan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btTambah.setText("Tambah");
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        btSelesai.setText("Selesai");
        btSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelesaiActionPerformed(evt);
            }
        });
        jPanel1.add(btSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, -1, -1));

        jLabel3.setText("Total Pembayaran :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        lbBayar.setText("-");
        jPanel1.add(lbBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 110, -1));

        jButton1.setText("Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboMenuActionPerformed

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        // TODO add your handling code here:
        //NANTI UBAH LAGi
        boolean b=false;
        Long s=null;
        int j=0;
        
        tbBayar.setValueAt(comboMenu.getSelectedItem(),i,0);
        for(int k=0; k<dr.item.size(); k++){
            if(comboMenu.getSelectedItem().equals(dr.item.get(k).name)){
                b=true;
                odtemp.item.add(dr.item.get(k));
                s=dr.item.get(k).price;
                tbBayar.setValueAt(s, i, 1);
                
            }
            
        }
        
        sum=sum+s;
        
       
//        for(int i=0; i<odtemp.item.size(); i++){
            System.out.println(odtemp.item.get(i).name);
//        }
        long tempD = 0;
        if(cs.state_member!=true){
            tempD=odtemp.item.size()*1000;
            lbDel.setText(""+tempD);
            
        }
        lbHarga.setText(""+sum);
        lbBayar.setText(""+(sum+tempD));
        //belum pakai random utk branch+staff
        String time=setTime();
        od=new Order(time, "o"+dr.order.size(), odtemp.item, cs, dr.branch.get(0).staff.get(0), dr.branch.get(0), cs.address);
        od.totalpayment=sum;
        i++;
    }//GEN-LAST:event_btTambahActionPerformed

    private void btSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelesaiActionPerformed
        // TODO add your handling code here:
        dr.order.add(od);
        try {
            dr.saveData(dr);
        } catch (IOException ex) {
            Logger.getLogger(OrderMakanan.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Data Pesanan berhasil disimpan !!");
        UserHome uh=new UserHome(dr);
        uh.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btSelesaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UserHome uh=new UserHome(dr);
        uh.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new OrderMakanan().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSelesai;
    private javax.swing.JButton btTambah;
    private javax.swing.JComboBox comboMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBayar;
    private javax.swing.JLabel lbDel;
    private javax.swing.JLabel lbHarga;
    private javax.swing.JTable tbBayar;
    // End of variables declaration//GEN-END:variables
}
