/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deliverymakanan;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yorozuya
 */
public class StaffHome extends javax.swing.JFrame {
    StaffForm sf;
    /**
     * Creates new form SaffHome
     */
    public StaffHome(StaffForm sf) {
        initComponents();
        this.setTitle("Home Staff");
        this.sf=sf;
        loadCustTable();
        loadItemTable();
        loadOrderTable();
        
    }
    public void loadCustTable(){
        for(int i=0; i<sf.dr.customer.size(); i++){
            tbPelanggan.setValueAt(sf.dr.customer.get(i).idcust, i, 0);
            tbPelanggan.setValueAt(sf.dr.customer.get(i).email, i, 1);
            tbPelanggan.setValueAt(sf.dr.customer.get(i).name, i, 2);
            tbPelanggan.setValueAt(sf.dr.customer.get(i).state_member, i, 3);
            tbPelanggan.setValueAt(sf.dr.customer.get(i).username, i, 4);
            tbPelanggan.setValueAt(sf.dr.customer.get(i).password, i, 5);
            tbPelanggan.setValueAt(sf.dr.customer.get(i).address, i, 6);
            tbPelanggan.setValueAt(sf.dr.customer.get(i).phone, i, 7);
        }
    }
    public void loadOrderTable(){
        for(int i=0; i<sf.dr.order.size(); i++){
            tbOrder.setValueAt(sf.dr.order.get(i).idorder, i, 0);
            tbOrder.setValueAt(sf.dr.order.get(i).orderdate, i, 1);
            tbOrder.setValueAt(sf.dr.order.get(i).cust.idcust, i, 2);
            tbOrder.setValueAt(sf.dr.order.get(i).deliverystaff.idstaff, i, 3);
            tbOrder.setValueAt(sf.dr.order.get(i).branch.idbranch, i, 4);
            tbOrder.setValueAt(sf.dr.order.get(i).stateDelivered, i, 5);
            tbOrder.setValueAt(sf.dr.order.get(i).statePayment, i, 6);
        }
    }
    public void loadItemTable(){
        for(int i=0; i<sf.dr.item.size(); i++){
            tbItem.setValueAt(sf.dr.item.get(i).iditem, i, 0);
            tbItem.setValueAt(sf.dr.item.get(i).name, i, 1);
            tbItem.setValueAt(sf.dr.item.get(i).price, i, 2);
            tbItem.setValueAt(sf.dr.item.get(i).stock, i, 3);
        }
    }
    public String toString(Object obj){
        return String.valueOf(obj);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPelanggan = new javax.swing.JTable();
        btReset = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbItem = new javax.swing.JTable();
        btReset1 = new javax.swing.JButton();
        btSave1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbOrder = new javax.swing.JTable();
        btReset2 = new javax.swing.JButton();
        btSave2 = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID cust", "email", "nama", "Status member", "username", "password", "alamat", "telp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbPelanggan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, 120));

        btReset.setText("Refresh");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        jPanel1.add(btReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        jTabbedPane1.addTab("Kelola Pelanggan", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID item", "Item_name", "Price", "Stock"
            }
        ));
        jScrollPane2.setViewportView(tbItem);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, 110));

        btReset1.setText("Refresh");
        btReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReset1ActionPerformed(evt);
            }
        });
        jPanel2.add(btReset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        btSave1.setText("Save");
        btSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSave1ActionPerformed(evt);
            }
        });
        jPanel2.add(btSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        jTabbedPane1.addTab("Kelola Item", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Order", "Date", "ID Customer", "ID Staff", "ID Branch", "State_Delivered", "State_Payment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbOrder);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, 120));

        btReset2.setText("Refresh");
        btReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReset2ActionPerformed(evt);
            }
        });
        jPanel3.add(btReset2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        btSave2.setText("Save");
        btSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSave2ActionPerformed(evt);
            }
        });
        jPanel3.add(btSave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        jTabbedPane1.addTab("Kelola Order", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 640, 320));

        btLogout.setText("Logout");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        sf.setVisible(true);
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReset2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            sf.dr=sf.dr.loadData();
        } catch (IOException ex) {
            Logger.getLogger(StaffHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadOrderTable();
    }//GEN-LAST:event_btReset2ActionPerformed

    private void btReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReset1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            sf.dr=sf.dr.loadData();
        } catch (IOException ex) {
            Logger.getLogger(StaffHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadItemTable();
    }//GEN-LAST:event_btReset1ActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        try {
            // TODO add your handling code here:
            sf.dr=sf.dr.loadData();
        } catch (IOException ex) {
            Logger.getLogger(StaffHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadCustTable();

    }//GEN-LAST:event_btResetActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
        ArrayList<Customer> cust=new ArrayList<>();

        int i=0;
        while(tbPelanggan.getValueAt(i, 0)!=null){
            
            Customer c=new Customer();
            String[] s=new String[8];
            for(int j=0; j<s.length; j++){
                s[j]=new String();
            }
            s[0]=toString(tbPelanggan.getValueAt(i, 2));
            s[1]=toString(tbPelanggan.getValueAt(i, 6));
            s[2]=toString(tbPelanggan.getValueAt(i, 1));
            s[3]=toString(tbPelanggan.getValueAt(i, 7));
            s[4]=toString(tbPelanggan.getValueAt(i, 4));
            s[5]=toString(tbPelanggan.getValueAt(i, 5));
            s[6]=toString(tbPelanggan.getValueAt(i, 0));
            
            c.setCustomer(s[0], s[1], s[2], s[3], s[4], s[5], s[6]);
            c.state_member=Boolean.valueOf(toString(tbPelanggan.getValueAt(i, 3)));
            cust.add(c);
            
            i++;
        }
        sf.dr.customer=cust;
        try {
            sf.dr.saveData(sf.dr);
        } catch (IOException ex) {
            Logger.getLogger(StaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Save data pelanggan berhasil !!");
    }//GEN-LAST:event_btSaveActionPerformed

    private void btSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSave1ActionPerformed
        // TODO add your handling code here:
        ArrayList<Item> item=new ArrayList<>();

        int i=0;
        while(tbItem.getValueAt(i, 0)!=null){
            String[] s=new String[8];
            for(int j=0; j<s.length; j++){
                s[j]=new String();
            }
            s[0]=toString(tbItem.getValueAt(i, 0));
            s[1]=toString(tbItem.getValueAt(i, 1));
            s[2]=toString(tbItem.getValueAt(i, 2));
            s[3]=toString(tbItem.getValueAt(i, 3));
            
            Item it=new Item(s[0], s[1], Integer.parseInt(s[3]), Long.parseLong(s[2]));

            item.add(it);
            
            i++;
        }
        sf.dr.item=item;
        try {
            sf.dr.saveData(sf.dr);
        } catch (IOException ex) {
            Logger.getLogger(StaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Save data Item berhasil !!");
        
    }//GEN-LAST:event_btSave1ActionPerformed

    private void btSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSave2ActionPerformed
        // TODO add your handling code here:
        ArrayList<Order> order=new ArrayList<>();

        
        int i=0;
        while(tbOrder.getValueAt(i, 0)!=null){
            String[] s=new String[8];
            for(int j=0; j<s.length; j++){
                s[j]=new String();
            }
            s[0]=toString(tbOrder.getValueAt(i, 0));
            s[1]=toString(tbOrder.getValueAt(i, 1));
            s[2]=toString(tbOrder.getValueAt(i, 2));
            s[3]=toString(tbOrder.getValueAt(i, 3));
            s[4]=toString(tbOrder.getValueAt(i, 4));
            s[5]=toString(tbOrder.getValueAt(i, 5));
            s[6]=toString(tbOrder.getValueAt(i, 6));
            
            Customer ctemp = null;
            Branch btemp = null;
            Staff stemp = null;
            Order odtemp = null;
            
            for(int j=0; j<sf.dr.order.size(); j++){
                if(s[0].equals(sf.dr.order.get(j).idorder)){
                    odtemp=sf.dr.order.get(j);
                }
            }
            for(int j=0; j<sf.dr.customer.size(); j++){
                if(s[2].equals(sf.dr.customer.get(j).idcust)){
                    ctemp=sf.dr.customer.get(j);
                }
            }
            
            for(int j=0; j<sf.dr.branch.size(); j++){
                if(s[4].equals(sf.dr.branch.get(j).idbranch)){
                    btemp=sf.dr.branch.get(j);
                }
            }
            for(int j=0; j<sf.dr.staff.size(); j++){
                if(s[3].equals(sf.dr.staff.get(j).idstaff)){
                    stemp=sf.dr.staff.get(j);
                }
            }
            
            Order od=new Order(s[1], odtemp.idorder, odtemp.item, ctemp, stemp, btemp, odtemp.address);
            od.stateDelivered=Boolean.valueOf(s[5]);
            od.statePayment=Boolean.valueOf(s[6]);
            order.add(od);
            
            i++;
        }
        sf.dr.order=order;
        try {
            sf.dr.saveData(sf.dr);
        } catch (IOException ex) {
            Logger.getLogger(StaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Save data Order berhasil !!");
    }//GEN-LAST:event_btSave2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StaffHome().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btReset1;
    private javax.swing.JButton btReset2;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSave1;
    private javax.swing.JButton btSave2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbItem;
    private javax.swing.JTable tbOrder;
    private javax.swing.JTable tbPelanggan;
    // End of variables declaration//GEN-END:variables
}
